### ISSUE TITLE
exec方法的文档有误，需要更正

### ISSUE THREAD

**Issue by sxei** [alipay/alipay-sdk-nodejs-all#103]
文档中写业务请求参数需要放到bizContent对象中，实际上不需要，文档最好更正过来，避免误导新人。
文档写法：
await alipaySdk.exec('alipay.system.oauth.token', {   
    bizContent: {
         grant_type: 'authorization_code',
         code: authCode,
    }
})
实际正确写法：
await alipaySdk.exec('alipay.system.oauth.token', {   
    grant_type: 'authorization_code',
    code: authCode,
})

**Comment by fengmk2** [comment]
@troyeagle 确认一下，如果是的话，更新文档。

**Comment by troyeagle** [comment]
`alipay.system.oauth.token` 比较特殊，它的参数涉及 SDK 的鉴权机制而非具体业务，故未放到 bizContent 当中。其他业务，还是需要 bizContent。
参考[开放平台 FAQ](https://opendocs.alipay.com/open/040mtt#Q%EF%BC%9A%E8%B0%83%E7%94%A8alipay.system.oauth.token%E6%8E%A5%E5%8F%A3%E7%9A%84%E5%B8%B8%E8%A7%81%E6%8A%A5%E9%94%99%E5%8F%8A%E8%A7%A3%E5%86%B3%E6%96%B9%E6%A1%88)。 我会修正文档表述并且增加示例。感谢反馈
