### ISSUE TITLE
有没有同样问题发生过。。实例化就报错：TypeError: AlipaySdk is not a constructor

### ISSUE THREAD

**Issue by tiyo** [alipay/alipay-sdk-nodejs-all#105]
刚安装，正常引入。。。实例化时，随即报错。。。

import AlipaySdk from 'alipay-sdk';
................(){
            this.pay = new AlipaySdk({
                appId: this.appid,
                privateKey: this.pri_key,
                alipayPublicKey: this.pub_key
            });
}

TypeError: AlipaySdk is not a constructor

**Comment by Hu-Wentao** [comment]
所以这个问题怎么解决的?

**Comment by tiyo** [comment]
随即放弃，，自己重写了一个。。简单、适合自己的才是最好的。。。

**Comment by Hu-Wentao** [comment]
> 随即放弃，，自己重写了一个。。简单、适合自己的才是最好的。。。

不可能吧, 这个是官方sdk, 我不太懂js, 不应该出现无法使用的情况. 跟node版本有关吗?我用的是18.0

**Comment by Hu-Wentao** [comment]
> 随即放弃，，自己重写了一个。。简单、适合自己的才是最好的。。。

找到了 https://opendoc.alipay.com/support/01raz7?pathHash=79b7ee3b
只需要这样
const AlipaySdk=require('alipay-sdk').default;
就行

**Comment by ryzencool** [comment]
用ES6模块怎么解决呀，这个还是TS的包呢，简直离谱，太难受了

**Comment by fengmk2** [comment]
如果是 ts，需要在 tsconfig.json 里面配置一下 esModuleInterop: true
