### ISSUE TITLE
在TS中，实例化报错AlipaySdk not a constructor

### ISSUE THREAD

**Issue by ryzencool** [alipay/alipay-sdk-nodejs-all#107]
如题

**Comment by ryzencool** [comment]
我的环境是 vite + sveltekit， 请给下解决方案，谢谢，在dev server是没问题的，但是build之后，会有 not a constructor 的问题

**Comment by silence-time** [comment]
我也遇到了，AlipaySdk not a constructor ，老哥咋解决的

**Comment by ryzencool** [comment]
没解决啊，换成调用java了

**Comment by Zjingwen** [comment]
@ryzencool 我是手写ci脚本碰到了这个问题。
```
import AlipaySdk from "alipay-sdk";
new AlipaySdk(
  // 具体配置
); // ---> 报错 TypeError: AlipaySdk.detail is not a constructor
```
```
import AlipaySdk from "alipay-sdk";
new AlipaySdk.default(
  // 具体配置
); // ---> 成功了
```

**Comment by hugepizza** [comment]
同样的问题 ts环境下es6 
```
import AlipaySdk from "alipay-sdk";
new AlipaySdk(config);
```
tsc编译出现异常: TypeError: AlipaySdk is not a constructor

```
❯ node -v
v20.4.0
❯ tsc -v
Version 5.1.6
```
希望你们作为官方团队能及时解决问题

**Comment by fengmk2** [comment]
按 编译结果 https://npmmirror.com/package/alipay-sdk/files?version=3.4.0

你需要在 tsconfig.json 里面配置一下 `esModuleInterop: true`

**Comment by fengmk2** [comment]
3.5.0 版本已经修复
