### ISSUE TITLE
授权信息加载失败

### ISSUE THREAD

**Issue by willin** [alipay/alipay-sdk-nodejs-all#115]
<img width="409" alt="image" src="https://github.com/alipay/alipay-sdk-nodejs-all/assets/1890238/ad8bcce7-051e-42ed-965c-9b50d482ac3c">

快捷登录
授权信息加载失败

为保证账号安全，建议你返回重新授权登录

https://opendocs.alipay.com/open/02aile?scene=common&pathHash=4efd837f

示例的代码为：

```js
const AlipaySdk = require("alipay-sdk").default;

const alipaySdk = new AlipaySdk({
  appId: "<-- 请填写您的AppId，例如：2019091767145019 -->",
  privateKey: "<-- 请填写您的应用私钥，例如：MIIEvQIBADANB ... ... -->",
  alipayPublicKey: "<-- 请填写您的支付宝公钥，例如：MIIBIjANBg... -->",
  gateway: "https://openapi-sandbox.dl.alipaydev.com/gateway.do",
});
const result = await alipaySdk.pageExec("alipay.user.info.auth", {
  bizContent: {
    state: "init",
    scopes: {
      0: "auth_base",
    },
  },
});
```

**Comment by fengmk2** [comment]
沙箱环境可能不够文档，建议使用生产环境试试。

欢迎前往 [支付宝开放社区](https://forum.alipay.com/mini-app/channel/1100001) 发帖与支付宝工作人员和其他开发者一起交流，
或联系 [支付宝开放平台客服](https://linksprod.alipay.com/app/room/5fec1e8f69565405716ba28a/) 协助解决。
