### ISSUE TITLE
生成的wap 订单链接，无法拉起沙盒版支付宝

### ISSUE THREAD

**Issue by newNcy** [alipay/alipay-sdk-nodejs-all#117]
![image](https://github.com/alipay/alipay-sdk-nodejs-all/assets/19602632/ec469d4b-b65d-47e9-9cff-ce5e5e8b569a)
切换到正式环境就能拉起支付宝

**Comment by newNcy** [comment]
跳转记录和日志如下

![image](https://github.com/alipay/alipay-sdk-nodejs-all/assets/19602632/2769bd8c-562e-4c1f-bf16-bebeaa5b872f)

**Comment by fengmk2** [comment]
这个不是 sdk 的问题了。

欢迎前往 [支付宝开放社区](https://forum.alipay.com/mini-app/channel/1100001) 发帖与支付宝工作人员和其他开发者一起交流，
或联系 [支付宝开放平台客服](https://linksprod.alipay.com/app/room/5fec1e8f69565405716ba28a/) 协助解决。
