### ISSUE TITLE
重构使用 支付宝 API v3 接口规范

### ISSUE THREAD

**Issue by fengmk2** [alipay/alipay-sdk-nodejs-all#120]
https://opendocs.alipay.com/open-v3/054oog?pathHash=7834d743 参考文档

- [x] 支付宝 API v3
- [x] tshy 同时支持 cjs 和 esm，参考 https://github.com/eggjs/egg/issues/5257
- [x] Node.js >= 18
- [ ] Release v4

这是一个 major version，会抛弃 Node.js < 18 的支持

**Comment by fengmk2** [comment]
alipay-request-id 使用 `crypto.randomUUID().replaceAll('-', '')` 生成

**Comment by popomore** [comment]
居然有新规范
