### ISSUE TITLE
exec 方法支持 AlipayFormStream 

### ISSUE THREAD

**Issue by StringKe** [alipay/alipay-sdk-nodejs-all#135]
目前 exec 方法需要 AlipayFormData 类型，这个类型无法直接设置 buffer 或者 stream 的类型作为文件内容，有诸多不便。

**Comment by fengmk2** [comment]
我加上 AlipayFormStream 的支持

**Comment by fengmk2** [comment]
@StringKe 是否可以使用 curl 的接口？exec 的 openapi v2 接口签名算法限制，毕竟难搞 stream。

**Comment by StringKe** [comment]
> @StringKe 是否可以使用 curl 的接口？exec 的 openapi v2 接口签名算法限制，毕竟难搞 stream。

可以主要是大部份文件都调度的 OSS 存储，需要把文件本地化之后才能提交上去，这个操作不太方便

**Comment by StringKe** [comment]
另一个是关于文件名字，支付宝的后台似乎是读取的 文件内容里的文件名字？比如 file("file_conent","a.jpg",path)

path 是 /tmp/xxxxxxx 随机字符串这种，接口会返回文件扩展不正确，fileName 似乎没有使用？

**Comment by fengmk2** [comment]
@StringKe https://github.com/alipay/alipay-sdk-nodejs-all/blob/master/test/alipay.test.ts#L169 你可以参考这个，使用 AlipayFormStream + curl 接口来上传文件，支持流式的，不需要将文件下载到本地。

**Comment by fengmk2** [comment]
https://github.com/alipay/alipay-sdk-nodejs-all/pull/134 @StringKe 可以参考这个文档，直接上传文件内容或者文件流，就不需要落盘了。

**Comment by fengmk2** [comment]
https://github.com/alipay/alipay-sdk-nodejs-all?tab=readme-ov-file#%E4%B8%8A%E4%BC%A0%E6%96%87%E4%BB%B6%E6%B5%81 我写了2个例子，你可以参考一下
