### ISSUE TITLE
需要批量付款的api和case

### ISSUE THREAD

**Issue by zhenmang** [alipay/alipay-sdk-nodejs-all#139]
您好，没找到批量付款相关的api。
需要批量付款的api和case，谢谢。

**Comment by fengmk2** [comment]
https://opendocs.alipay.com/open-v3/2423fad5_alipay.trade.page.pay?scene=22&pathHash=cb11d6e0 可以到支付宝开放平台自行查看相关 api 文档

**Comment by zhenmang** [comment]
您好，您的邮件我已收到

**Comment by zhenmang** [comment]
里面没有批量付款的api。但之前确实在阿里的一些文档上看到过支付宝有对外批量付款的api

**Comment by fengmk2** [comment]
那我就不知道了，以支付宝开放平台的文档为主。

**Comment by zhenmang** [comment]
这个是不是支付宝开放平台的文档呀
https://developer.alibaba.com/docs/doc.htm?treeId=64&articleId=103569&docType=1

**Comment by fengmk2** [comment]
![image](https://github.com/alipay/alipay-sdk-nodejs-all/assets/156269/4b76aae4-d2b1-4249-8f2a-cae3fb80fa2e)
这个不是支付宝开放平台
