### ISSUE TITLE
 Cannot find name 'ErrorOptions'

### ISSUE THREAD

**Issue by WihteCrow** [alipay/alipay-sdk-nodejs-all#152]
https://github.com/alipay/alipay-sdk-nodejs-all/blob/796b55a2152a53f47767870fcd04665ad5a3ceac/src/alipay.ts#L37C52-L37C64

**Comment by YuriArthas** [comment]
Hi, How did it work? It happened to me...
()怎么解决的啊老哥)

**Comment by WihteCrow** [comment]
官方处理太慢，我弄了一个修正版：npm install alipay-sdk-patched
https://www.npmjs.com/package/alipay-sdk-patched

**Comment by fengmk2** [comment]
按要求至少依赖 Node.js >= 18
https://github.com/alipay/alipay-sdk-nodejs-all/blob/master/package.json#L5
