### ISSUE TITLE
开启了aes加密怎么配置form，好像没有找到啊

### ISSUE THREAD

**Issue by newbreach** [alipay/alipay-sdk-nodejs-all#16]

**Comment by tudou527** [comment]
sdk 暂时没有提供 aes 加密的功能

**Comment by briefguo** [comment]
😰😰😰

有关闭aes加密吗。。

**Comment by briefguo** [comment]
有没有比较好的，带AES加解密的实践，可以参考的吗？

**Comment by tudou527** [comment]
@briefguo  aes 加密相关的文档：https://docs.open.alipay.com/common/104567。我这周会增加 aes 加密相关的功能

**Comment by briefguo** [comment]
好的，多谢🙏。

发自我的 iPhone

**Comment by HandsomeWolf** [comment]
你好，请问aes解密功能如何使用？
文档说明中，“AES加密”页找不到了
https://www.yuque.com/chenqiu/alipay-node-sdk/aes

**Comment by tudou527** [comment]
还没开发完

**Comment by HandsomeWolf** [comment]
`    @Post('getPhone')
    async getPhone(@Body() body) {
        let response = 'XXXX'

        var key = "XXXX";

        var iv = CryptoJS.enc.Hex.parse("0000000000000000");
        //解密
        response = CryptoJS.enc.Base64.parse(response);
        var decrypt = CryptoJS.AES.decrypt(response, key, {
            mode: CryptoJS.mode.CBC,
            padding: CryptoJS.pad.Pkcs7,
        })
        console.log(decrypt);
        console.log(decrypt.toString(CryptoJS.enc.Utf8));
        return decrypt
    }`
我不清楚AES加密时的模式、填充、偏移量，但各种值都试过了结果始终是{ words: [], sigBytes: 0 }
