### ISSUE TITLE
下单出现 ret.status === 200，ret.data 是个 html 的情况，然后 JSON.parse(ret.data)出问题

### ISSUE THREAD

**Issue by heibai01** [alipay/alipay-sdk-nodejs-all#50]
// egg app/extend/application.js

```js
  async getAlipayClient() {
    if (!this[ALIPAY]) {
      // this.config.alipay.notifyUrl = await this.createAnonymousContext().serverRequest.getServiceUrl('ms-order') + '/order/payNotify/alipay';
      this[ALIPAY] = new AlipaySdk(this.config.alipay);
    }
    return this[ALIPAY];
  },
```

// 下单代码
```js
      const ali = await ctx.app.getAlipayClient();
      const notifyUrl = await ctx.serverRequest.getServiceUrl('ms-order') + '/order/payNotify/alipay';
      const bizContent = {
        subject: order.title,
        timeoutExpress: '10m',
        totalAmount: String(order.amount),
        outTradeNo: orderSn,
      };
      let result = {};
      if (query.alipayMode === 'APP') {
        result = {
          payData: await ali.exec('alipay.trade.app.pay', {
            notifyUrl,
            charset: 'GBK',
            bizContent,
          }),
        };
```

Debug 如下图所示：

<img width="929" alt="5EC9EAF3-EE07-4A9C-BB77-6C3CF827CDB9" src="https://user-images.githubusercontent.com/7297860/67823011-65e94600-fafc-11e9-8709-3a1342deeec6.png">

**Comment by tudou527** [comment]
参数出错了，这是个错误页面。

**Comment by heibai01** [comment]
一个最简单的 app 支付，总得告诉我是哪个参数出错了吧？
https://docs.open.alipay.com/api_1/alipay.trade.app.pay

**Comment by tudou527** [comment]
https://www.yuque.com/chenqiu/alipay-node-sdk/page_api#SyhyY

**Comment by heibai01** [comment]
![image](https://user-images.githubusercontent.com/7297860/67825389-2161a880-fb04-11e9-849c-04bd2f9d7294.png)

我初衷是要用这个 `alipay.trade.page.pay` 这个方式，用了表单传参的方式，一样的问题。
所以我就看看 `alipay.trade.app.pay` 这种 APP 支付的，这种传参比较简单，想跑通下流程，可是得的却是一个 HTML。

**Comment by heibai01** [comment]
`alipay.trade.page.pay` 这个调通了，我把 formData 放在外层了，没有这样 { formData }。

那这种非页面类的，我是要在 APP 内部发起原生支付宝APP支付的，使用`alipay.trade.app.pay`这个应该没问题吧，我上面的贴的代码示例有问题吗？应该接收一个 JSON 数据的呀。

**Comment by smilence86** [comment]
@heibai01 解决了吗？我也是一样的问题，请求alipay.trade.query能得到一个json结果，alipay.trade.app.pay就是http 302跳转，不知道是不是sdk的bug，官方文档写明应该是json格式呀
