### ISSUE TITLE
checkNotifySign返回false

### ISSUE THREAD

**Issue by jyj545** [alipay/alipay-sdk-nodejs-all#68]
checkNotifySign返回false，请问这个问题解决了吗？
alipaySdk.checkNotifySign( this.req.body )

**Comment by tinytinysun** [comment]
我也遇到这个问题，个别应用账号延签成功，个别应用账号延签失败

**Comment by tinytinysun** [comment]
> checkNotifySign返回false，请问这个问题解决了吗？
> alipaySdk.checkNotifySign( this.req.body )

我参考这个解决了
https://github.com/alipay/alipay-sdk-nodejs-all/issues/45#issuecomment-536653023

**Comment by fengmk2** [comment]
使用 checkNotifySignV2
