### ISSUE TITLE
Replace deprecated request dependency

### ISSUE THREAD

**Issue by perrin4869** [alipay/alipay-sdk-nodejs-all#72]
[request](https://www.npmjs.com/package/request) was deprecated earlier this year. Moreover, it has dependencies on problematic modules like [sshpk](https://github.com/joyent/node-sshpk/issues/42). It should be possible to migrate to [bent](https://www.npmjs.com/package/bent) by the same developer.
`urllib` could be replaced by `bent` as well, also removing [problematic](https://github.com/nodejs/readable-stream/issues/348) [dependencies](https://www.npmjs.com/package/ftp) and reducing the SDK size.
Would you be willing to merge a PR implementing these changes?

**Comment by TheNorthMemory** [comment]
Here's another fully re-designed javascript SDK, less dependices(minimal only need `axios`). With `yargs`, it's possible play the OpenAPI requests over command line. Repo here: https://github.com/TheNorthMemory/whats-alipay
