### ISSUE TITLE
证书模式签名报错

### ISSUE THREAD

**Issue by cffycls** [alipay/alipay-sdk-nodejs-all#80]
// 计算签名
    const sign = crypto.createSign(ALIPAY_ALGORITHM_MAPPING[config.signType])
        .update(signStr, 'utf8').sign(config.privateKey, 'base64');
通过打断点和日志确定是 sign(config.privateKey, 'base64') 这步的问题，该怎么解决

-------------------------------------------  

opensslErrorStack: [
    'error:04093004:rsa routines:old_rsa_priv_decode:RSA lib',
    'error:0D08303A:asn1 encoding routines:asn1_template_noexp_d2i:nested asn1 error',
    'error:0D06C03A:asn1 encoding routines:asn1_d2i_ex_primitive:nested asn1 error'
  ],
  library: 'asn1 encoding routines',
  function: 'asn1_check_tlen',
  reason: 'wrong tag',
  code: 'ERR_OSSL_ASN1_WRONG_TAG'

**Comment by hhgz9527** [comment]
+1，我也遇到这个问题，请问你解决了吗？

**Comment by hhgz9527** [comment]
发现是证书问题..重新上传了下，好了

**Comment by cffycls** [comment]
我修改了官方的代码，去掉依赖就好了



---原始邮件---
发件人: "GaoYu"<notifications@github.com&gt;
发送时间: 2020年12月3日(周四) 下午5:30
收件人: "alipay/alipay-sdk-nodejs-all"<alipay-sdk-nodejs-all@noreply.github.com&gt;;
抄送: "cffycls"<cffycls@foxmail.com&gt;;"Author"<author@noreply.github.com&gt;;
主题: Re: [alipay/alipay-sdk-nodejs-all] 证书模式签名报错 (#80)




 
+1，我也遇到这个问题，请问你解决了吗？
 
—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
 
---原始邮件---
发件人: "GaoYu"<notifications@github.com&gt;
发送时间: 2020年12月3日(周四) 下午5:30
收件人: "alipay/alipay-sdk-nodejs-all"<alipay-sdk-nodejs-all@noreply.github.com&gt;;
抄送: "cffycls"<cffycls@foxmail.com&gt;;"Author"<author@noreply.github.com&gt;;
主题: Re: [alipay/alipay-sdk-nodejs-all] 证书模式签名报错 (#80)




 
+1，我也遇到这个问题，请问你解决了吗？

**Comment by leohuangyi** [comment]
新版支付宝开发平台助手中，私钥要：转PKCS1(非JAVA适用)私钥 才行

**Comment by shaokun11** [comment]
初始化的时候加上keyType,即可解决,因为按照支付宝的流程生成的私钥类型是pkcs8,实例化的时候回formatKey,不加的话默认实例化成了 "RSA PRIVATE KEY"这种类型了
`const alipaySdk = new AlipaySdk({
    appId: CONFIG.ALI_PAY.appid,
    keyType: 'PKCS8'
})`

**Comment by jjj201200** [comment]
<img width="434" alt="image" src="https://user-images.githubusercontent.com/3397549/220008886-34d21db2-6e8c-42e8-a1c7-fbf45fc64287.png">
他们知道！但是他们不写在文档里！

**Comment by pandafeeeder** [comment]
服气，这么重要的说明不写在文档里

**Comment by fengmk2** [comment]
默认已经是 RSA2 了
