### ISSUE TITLE
aes加密请求，response验签失败--严重bug

### ISSUE THREAD

**Issue by yangguangqishimi** [alipay/alipay-sdk-nodejs-all#82]
![image](https://user-images.githubusercontent.com/29886722/109786097-bac33200-7c04-11eb-83dc-26112bb1834e.png)
alipay.js 227行
因为validateStr 在220行已经被截取过了，所以再截取0，lastIndex，就去不掉"sign"后面的字符串了。
但是由于不采用aes加密是，229行和231行，去除了{}前后的字符串，避开了上诉截取不正确的问题，因此没问题。
当请求“alipay.open.auth.app.aes.get”时，由于必须使用aes加密，返回的response是加密后的字符串，而不是json字符串，所以229和231行就不起作用了，这样最后得到的validateStr就是错的，类似这样的 ":"hYef4GFklQOxJtbDvUVGPP6XPXXjjC392caT1xw+YpzXl0/tzIQGA3jHI8GCkTnp","sign":"VdYhyyjnc6tleQjzzVRoFgj/UeMMOy97"
所以，验签失败
![image](https://user-images.githubusercontent.com/29886722/109787200-e2ff6080-7c05-11eb-8f63-2601072dbacb.png)

**Comment by fengmk2** [comment]
使用最新版本的 sdk，默认会做响应验签。
